# Generated by Django 3.1.7 on 2021-03-10 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlackCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blancks', models.IntegerField(default=1)),
                ('phrase', models.CharField(default='', max_length=300)),
                ('blanck_idx', models.IntegerField(blank=True, default=1)),
            ],
        ),
        migrations.CreateModel(
            name='GameGroup',
            fields=[
                ('group_id', models.IntegerField(default=1, primary_key=True, serialize=False, unique=True)),
                ('total_matchs', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.IntegerField(default=1, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=150)),
                ('total_matchs', models.IntegerField(default=1)),
                ('total_points', models.IntegerField(default=1)),
                ('total_wons', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='WhiteCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField(default=1)),
                ('group_id', models.IntegerField(default=1)),
                ('score', models.IntegerField(default=1)),
                ('matchs_won', models.IntegerField(default=1)),
                ('matchs_played', models.IntegerField(default=1)),
                ('group_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cahserver.gamegroup')),
            ],
        ),
        migrations.AddField(
            model_name='gamegroup',
            name='players',
            field=models.ManyToManyField(to='cahserver.Player'),
        ),
    ]
