# Generated by Django 3.1.7 on 2021-03-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cahserver', '0003_auto_20210312_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamegroup',
            name='players',
        ),
        migrations.RemoveField(
            model_name='scoreentry',
            name='group_object',
        ),
        migrations.AddField(
            model_name='scoreentry',
            name='player_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='blackcard',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scoreentry',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='whitecard',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
